Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/groovy64"
    config.vm.hostname = "testServer"
    config.vm.network "public_network"
    config.vm.provider "virtualbox" do |v|
        v.memory = 4000
        v.cpus = 2
        v.name = "test_server_for_ansible"
    end
    config.vm.provision "shell", path: "testServer_provision.sh"
end